modify “PhantomJS:page.onError - msg: TypeError: undefined is not a function”
https://stackoverflow.com/questions/39713918/phantomjspage-onerror-msg-typeerror-undefined-is-not-a-function
Error is occurring due to "datasetbutton.click();" line. If you remove that line then you will not get error but i need that 'click' to generate result. So which Phantomjs is compatible with Selenium 2.53.1 version